### PR TITLE
Fixes harvester bug for high gcl and energy <= 350

### LINKED ISSUE #585: Harvester problem with only 300 energy in room on higher RCL
It seems that there is an issue with harvesters: https://github.com/TooAngel/screeps/pull/581#discussion_r464626547

The best approach would be to write tests for different cases and see when it fails. Any other solution is fine, too :-)

### PR DESCRIPTION
**Pull request by Kill4Free**
Fixed creep builder updateSettings function. (lodash merge)
Harvester prefers empty spawns and extensions before anything else.
Added logging to config.debug.spawn.
Cleared unnecessary stuff from harvester.updateSettings.

Fixes #585

### CODE REVIEW

**Comment by TooAngel** [comment]
This pull request will be automatically merged by [worlddriven](https://www.worlddriven.org) in 9 days and 23 hours.
Check the `worlddriven` status checks or the [dashboard](https://www.worlddriven.org/TooAngel/screeps/pull/589) for actual stats.

`Approved` reviews will speed this up.
`Request Changes` reviews will slow it down or stop it.

File: src/config_brain_stats.js [hunk 1]
```diff
@@ -62,6 +62,7 @@ brain.stats.add = function(path, newContent) {
     current = current[item];
   }
 
+  // Redundant _.merge automatically alters first object
```
Comment (TooAngel) [inline src/config_brain_stats.js:65]: If it is redundant, just fix it (thx, for pointing out)

File: src/prototype_creep_resources.js [hunk 2]
```diff
@@ -726,9 +726,18 @@ Creep.prototype.construct = function() {
 };
 
 Creep.prototype.getTransferTargetStructure = function() {
-  const structure = this.pos.findClosestStructureWithMissingEnergyByRange(
+  let structure = this.pos.findClosestStructureWithMissingEnergyByRange(
     (object) => object.structureType !== STRUCTURE_STORAGE,
   );
+  // Harvester should always prefer Spawn and Extensions
```
Comment (TooAngel) [inline src/prototype_creep_resources.js:732]: Harvester only uses this method before the storage is built, so the only structures are `SPAWN`, `EXTENSION`, and `TOWER`. Because of invaders and early attacks, I think it is a good idea to have the `TOWER` filled, too.

As soon as the storage is built up (and has enough energy) it will move on a fixed path and only fills spawns and extensions. I could only see issues at that point when also other structures are available.

So fine leave it in right now, but needs to be verified in early scenarios regarding the tower.

File: src/prototype_room_creepbuilder.js [hunk 3]
```diff
@@ -211,7 +211,14 @@ Room.prototype.getPartsStringDatas = function(parts, energyAvailable) {
 Room.prototype.getSettings = function(creep) {
   const role = creep.role;
   const updateSettings = roles[role].updateSettings && roles[role].updateSettings(this, creep);
-  const settings = _.merge(roles[role].settings, updateSettings);
+  if (config.debug.spawn) {
```
Comment (TooAngel) [inline src/prototype_room_creepbuilder.js:214]: Instead of having the `if clause` here, you can use the `debugLog`, like:
```this.debugLog('spawn', `getSettings updateSettings: ${JSON.stringify(updateSettings)}`);``` (checkout `logging.js`)
which reduces the complexity in this methods and has the same functionality.

File: src/prototype_room_creepbuilder.js [hunk 4]
```diff
@@ -211,7 +211,14 @@ Room.prototype.getPartsStringDatas = function(parts, energyAvailable) {
...
+    this.log(`getSettings updateSettings: ${JSON.stringify(updateSettings)}`);
+    this.log(`getSettings roles[role].settings: ${JSON.stringify(roles[role].settings)}`);
+  }
+  const settings = _.merge({}, roles[role].settings, updateSettings);
```
Comment (TooAngel) [inline src/prototype_room_creepbuilder.js:218]: Wow, nice catch, tricky to find, thx

**Review by TooAngel — APPROVED** [review]
Looks good, thx, nice catch.

Maybe if you change the debug logging to `Room.debugLog` we also get rid of the codeclimate issues.

File: src/config_brain_stats.js (hunk 1 above)
Comment (Kill4Free) [reply src/config_brain_stats.js:65]: Okay will fix it if I've got some spare time!

File: src/prototype_creep_resources.js (hunk 2 above)
Comment (Kill4Free) [reply src/prototype_creep_resources.js:732]: I had a problem while all buildings were done. There was just an harvester from the previous bug and this harvester only filled the `TERMINAL`.
The tower would be filled after the room is working smootly again don't know if that brings a problem in the early stages.

File: src/prototype_room_creepbuilder.js (hunk 3 above)
Comment (Kill4Free) [reply src/prototype_room_creepbuilder.js:214]: Oh I overlooked that I will change these accordingly.

File: src/prototype_room_creepbuilder.js (hunk 4 above)
Comment (Kill4Free) [reply src/prototype_room_creepbuilder.js:218]: Yeah took me some time to find it but in the end I found it :-)

File: src/prototype_creep_resources.js (hunk 2 above)
Comment (TooAngel) [reply src/prototype_creep_resources.js:732]: Ok, let's leave it like this. I don't like special cases so much, but better be robust for now.

**Comment by TooAngel** [comment]
This pull request was merged by [worlddriven](https://www.worlddriven.org).
